{
 "title": "Test-Volume dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(k8s_pod_pv_usage_bytes,namespace)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(k8s_pod_pv_usage_bytes,cluster)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(k8s_pod_pv_available_bytes,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Usage Trend",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum(k8s_pod_pv_usage_bytes{pod!=\"\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod pv by volume name",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(k8s_pod_pv_usage_bytes{pod=~\".*$pod\",pod!=\"\",namespace=~\".*$namespace\",cluster=\"$cluster\"}) by (pod,name)"
    },
    {
     "expr": "sum(k8s_pod_pv_available_bytes{pod=~\".*$pod\",pod!=\"\",namespace=~\".*$namespace\",cluster=\"$cluster\"}) by (pod,name)"
    },
    {
     "expr": "sum(k8s_pod_pv_capacity_bytes{pod=~\".*$pod\",pod!=\"\",namespace=~\".*$namespace\",cluster=\"$cluster\"}) by (pod,name)"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(k8s_pod_pv_usage_bytes{namespace=~\"$namespace.*\" ,pod!= \"\"}) by (pod)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(k8s_pod_pv_available_bytes{namespace=~\"$namespace.*\",pod!= \"\"}) by (pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(k8s_pod_pv_capacity_bytes{namespace=~\"$namespace.*\",pod!= \"\"}) by (pod)",
     "legendFormat": "Capacity"
    },
    {
     "expr": "(sum(k8s_pod_pv_usage_bytes{namespace=~\"$namespace.*\",pod!= \"\"}) by (pod)/sum(k8s_pod_pv_available_bytes{namespace=~\"$namespace.*\"}) by (pod)) *100",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}